services:
  llm-agent:
    image: deployment.keeplearningos.com:5000/insights/llm-agent:latest
    container_name: insights-llm-agent
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    command: python app.py
